# Generated by Django 3.2.13 on 2022-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='click_upgrade_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_data',
            name='click_upgrade_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_data',
            name='click_upgrade_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_data',
            name='click_upgrade_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_data',
            name='cookie_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_data',
            name='factory_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_data',
            name='grandma_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game_data',
            name='level',
            field=models.BigIntegerField(default=0),
        ),
    ]
