# Generated by Django 4.0.5 on 2022-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='cookie_number',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='factory_number',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='grandma_number',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='level',
            field=models.FloatField(default=1),
        ),
    ]
