# Generated by Django 3.2.13 on 2022-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20220520_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='level',
            field=models.BigIntegerField(default=1),
        ),
    ]
