# Generated by Django 4.0.5 on 2022-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_game_data_cookie_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='exp',
            field=models.BigIntegerField(default=0),
        ),
    ]
