# Generated by Django 4.0.5 on 2022-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_game_data_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='exp',
            field=models.FloatField(default=0),
        ),
    ]
