# Generated by Django 4.0.5 on 2022-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_game_data_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='exp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='factory_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='grandma_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='level',
            field=models.BigIntegerField(default=1),
        ),
    ]
